from day7 import FileSystem, FileType, DirType
root = DirType('/')
a = FileSystem('a', 'dir')
b = FileType('b.txt', size=14848514)
c = FileType('c.dat', size=8504156)
e = FileSystem('e', 'dir')
i = FileType('i', size=584)
f = FileType('f', size=29116)
g = FileSystem('g', 'file', size=2557)
h = FileSystem('h.lst', 'file', size=62596)

d = FileSystem('d', 'dir')
j = FileSystem('j', 'file', size=4060174)
dd = FileSystem('d.log', 'file', size=8033020)
dd1 = FileSystem('d.ext', 'file', size=5626152)
k = FileSystem('k', 'file', size=7214296)

root.add_file(a)
root.add_file(b)
root.add_file(c)
a.add_file(e)
a.add_file(f)
a.add_file(g)
a.add_file(h)
e.add_file(i)
root.add_file(d)
d.add_file([j,dd,dd1,k])
print(root)
print(a.size_of())
print(d.size_of())
print(root.size_of())

cc = set()
cc.add(a)
cc.add(a)